import PDFDocument from 'pdfkit';
import { Response } from 'express';
import { ReportColumn } from './csv';

const CLINIC_NAME = 'MediCare Clinic & Dispensary';

export interface ReportPayload {
  title: string;
  range?: { from?: Date | string; to?: Date | string };
  columns: ReportColumn[];
  rows: Record<string, unknown>[];
  summary?: Record<string, unknown>;
}

const formatCell = (value: unknown): string => {
  if (value === null || value === undefined) return '';
  if (value instanceof Date) return value.toISOString().slice(0, 10);
  if (typeof value === 'number') return Number.isInteger(value) ? String(value) : value.toFixed(2);
  return String(value);
};

// Watermarked per export (SEC-11) so a leaked PDF can be traced back to who pulled it and when.
export const streamReportPdf = (payload: ReportPayload, generatedBy: string, res: Response) => {
  const doc = new PDFDocument({ margin: 40, size: 'A4', layout: 'landscape' });
  doc.pipe(res);

  doc.fontSize(16).text(CLINIC_NAME, { align: 'center' });
  doc.fontSize(13).text(payload.title, { align: 'center' });
  doc.fontSize(9).fillColor('#555');
  const rangeText = payload.range
    ? `Range: ${payload.range.from ? formatCell(new Date(payload.range.from as any)) : '—'} to ${payload.range.to ? formatCell(new Date(payload.range.to as any)) : '—'}`
    : '';
  doc.text(`Generated by ${generatedBy} on ${new Date().toISOString().slice(0, 19).replace('T', ' ')}${rangeText ? '  |  ' + rangeText : ''}`, {
    align: 'center',
  });
  doc.fillColor('black').moveDown();

  if (payload.summary && Object.keys(payload.summary).length > 0) {
    doc.fontSize(10).fillColor('#333');
    const summaryLine = Object.entries(payload.summary)
      .map(([k, v]) => `${k}: ${formatCell(v)}`)
      .join('    ');
    doc.text(summaryLine);
    doc.fillColor('black').moveDown();
  }

  const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
  const colWidth = pageWidth / payload.columns.length;
  const startX = doc.page.margins.left;

  const drawRow = (values: string[], y: number, bold: boolean) => {
    doc.font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(9);
    values.forEach((val, i) => {
      doc.text(val, startX + i * colWidth, y, { width: colWidth - 5, ellipsis: true });
    });
  };

  let y = doc.y;
  drawRow(payload.columns.map((c) => c.label), y, true);
  y += 16;
  doc.moveTo(startX, y - 3).lineTo(startX + pageWidth, y - 3).strokeColor('#ccc').stroke();

  for (const row of payload.rows) {
    if (y > doc.page.height - doc.page.margins.bottom - 20) {
      doc.addPage();
      y = doc.page.margins.top;
    }
    drawRow(
      payload.columns.map((c) => formatCell(row[c.key])),
      y,
      false
    );
    y += 15;
  }

  if (payload.rows.length === 0) {
    doc.fontSize(9).fillColor('#777').text('No data in this range.', startX, y);
  }

  doc.end();
};
